version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./konteneryzacja_fizjo 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres  
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_INITIALIZE: true
    depends_on:
      - postgres
    ports:
      - "8081:8081"  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  
    depends_on:
      - backend
    ports:
      - "3004:3004"   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
